### PR TITLE
Universal confirmation

### PR DESCRIPTION
**Pull request by pottzman**

### CODE REVIEW

**Comment by CONIGUERO** [comment]
```
[ 45%] Building CXX object CMakeFiles/_umskt.dir/src/libumskt/libumskt.cpp.o
/home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp: In function 'int ConfirmationID_Generate(const char*, char*, int)':
/home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp:31:36: error: no matching function for call to 'ConfirmationID::Generate(const char*&, char*&)'
   31 |     return ConfirmationID::Generate(installation_id_str, confirmation_id);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp:24:
/home/runner/work/UMSKT/UMSKT/src/libumskt/confid/confid.h:68:16: note: candidate: 'static int ConfirmationID::Generate(const char*, char*, int)'
   68 |     static int Generate(const char* installation_id_str, char confirmation_id[49], int activationMode);
      |                ^~~~~~~~
/home/runner/work/UMSKT/UMSKT/src/libumskt/confid/confid.h:68:16: note:   candidate expects 3 arguments, 2 provided
make[2]: *** [CMakeFiles/_umskt.dir/build.make:76: CMakeFiles/_umskt.dir/src/libumskt/libumskt.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/_umskt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Error: Process completed with exit code 2.
```

**Comment by CONIGUERO** [comment]
Failed again.

```
/home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp: In function 'int ConfirmationID_Generate(const char*, char*, int)':
/home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp:31:36: error: no matching function for call to 'ConfirmationID::Generate(const char*&, char*&)'
   31 |     return ConfirmationID::Generate(installation_id_str, confirmation_id);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/runner/work/UMSKT/UMSKT/src/libumskt/libumskt.cpp:24:
/home/runner/work/UMSKT/UMSKT/src/libumskt/confid/confid.h:68:16: note: candidate: 'static int ConfirmationID::Generate(const char*, char*, int)'
   68 |     static int Generate(const char* installation_id_str, char confirmation_id[49], int activationMode);
      |                ^~~~~~~~
/home/runner/work/UMSKT/UMSKT/src/libumskt/confid/confid.h:68:16: note:   candidate expects 3 arguments, 2 provided
make[2]: *** [CMakeFiles/_umskt.dir/build.make:76: CMakeFiles/_umskt.dir/src/libumskt/libumskt.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/_umskt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Error: Process completed with exit code 2.
```

**Comment by CONIGUERO** [comment]
Could you try to build the changes lically yourself before committing them to the PR? (If you aren't already)

**Comment by thepwrtank18** [comment]
bro how does your ide not squiggly line all that

**Comment by CONIGUERO** [comment]
Same error except now it's 4 arguments instead of 3.

Are you sure it builds for you?

**Comment by CONIGUERO** [comment]
The exact same error as before.

@pottzman Are you testing your code locally before pushing?

**Comment by thepwrtank18** [comment]
I'm genuinely cutious what your code environment is.

(Please don't tell me it's Notepad)

**Pull request closed without merging**
